package ai

import (
	"context"
	"encoding/json"
	"fmt"
	"regexp"
	"strings"
	"time"

	"github.com/sirupsen/logrus"
)

// InteractionEngine AI驱动的交互引擎
type InteractionEngine struct {
	client *Client
	logger *logrus.Logger
}

// NewInteractionEngine 创建交互引擎
func NewInteractionEngine(apiKey string, logger *logrus.Logger) *InteractionEngine {
	return &InteractionEngine{
		client: NewClient(apiKey, logger),
		logger: logger,
	}
}

// Action 交互动作
type Action struct {
	Type     string `json:"type"`     // click, input, scroll
	X        int    `json:"x,omitempty"`
	Y        int    `json:"y,omitempty"`
	Value    string `json:"value,omitempty"`    // input类型的输入值
	Direction string `json:"direction,omitempty"` // scroll方向: up/down
	Reason   string `json:"reason"`
	Priority int    `json:"priority"` // 1-16, 数字越大越优先
}

// PlanActions 分析UI并生成交互策略
func (e *InteractionEngine) PlanActions(ctx context.Context, uiData *UIData, activityName string, appCategory string) ([]Action, error) {
	// 检查是否有可交互元素
	if len(uiData.ClickableElements) == 0 && len(uiData.InputFields) == 0 {
		e.logger.Info("No interactive elements found")
		return []Action{}, nil
	}

	// 构建Prompt
	prompt := e.buildAnalysisPrompt(uiData, activityName, appCategory)

	// 调用AI分析 (使用纯文本模式,不使用截图)
	aiResponse, err := e.callAI(ctx, prompt)
	if err != nil {
		e.logger.WithError(err).Warn("AI call failed, using fallback strategy")
		return e.fallbackStrategy(uiData, activityName), nil
	}

	// 解析AI响应
	actions := e.parseAIResponse(aiResponse, uiData)
	if len(actions) == 0 {
		e.logger.Warn("No actions generated by AI, using fallback")
		return e.fallbackStrategy(uiData, activityName), nil
	}

	// 动态限制操作数
	maxActions := CalculateMaxActions(uiData)
	if len(actions) > maxActions {
		actions = actions[:maxActions]
	}

	return actions, nil
}

// buildAnalysisPrompt 构建AI分析提示词
func (e *InteractionEngine) buildAnalysisPrompt(uiData *UIData, activityName string, appCategory string) string {
	// 判断是否是主Activity
	isMainActivity := strings.Contains(strings.ToLower(activityName), "main") ||
		strings.Contains(strings.ToLower(activityName), "launcher") ||
		strings.Contains(strings.ToLower(activityName), "splash") ||
		strings.Contains(strings.ToLower(activityName), "welcome")

	// 简化可点击元素信息
	clickableSummary := []string{}
	for i, elem := range uiData.ClickableElements {
		if i >= 15 { // 最多15个
			break
		}

		displayText := elem.Label
		if displayText == "" {
			displayText = elem.Text
		}

		resourceIDShort := ""
		if elem.ResourceID != "" {
			parts := strings.Split(elem.ResourceID, "/")
			if len(parts) > 0 {
				resourceIDShort = parts[len(parts)-1]
			}
		}

		classShort := ""
		if elem.Class != "" {
			parts := strings.Split(elem.Class, ".")
			if len(parts) > 0 {
				classShort = parts[len(parts)-1]
			}
		}

		summary := fmt.Sprintf("%d. ", i+1)
		if displayText != "" {
			summary += fmt.Sprintf("文本:\"%s\" ", displayText)
		}
		if resourceIDShort != "" {
			summary += fmt.Sprintf("ID:%s ", resourceIDShort)
		}
		summary += fmt.Sprintf("类型:%s 坐标:(%d,%d)", classShort, elem.Center[0], elem.Center[1])

		clickableSummary = append(clickableSummary, summary)
	}

	// 输入框信息
	inputSummary := []string{}
	for i, elem := range uiData.InputFields {
		if i >= 5 { // 最多5个
			break
		}

		summary := fmt.Sprintf("%d. ", i+1)
		if elem.Text != "" {
			summary += fmt.Sprintf("默认文本:\"%s\" ", elem.Text)
		}
		if elem.ResourceID != "" {
			parts := strings.Split(elem.ResourceID, "/")
			if len(parts) > 0 {
				summary += fmt.Sprintf("ID:%s ", parts[len(parts)-1])
			}
		}
		summary += fmt.Sprintf("坐标:(%d,%d)", elem.Center[0], elem.Center[1])

		inputSummary = append(inputSummary, summary)
	}

	// 检测特殊按钮
	hasSkipLogin := false
	hasLoginButton := false
	hasBrowsableContent := len(uiData.ClickableElements) > 5 || len(uiData.ScrollableViews) > 0

	skipKeywords := []string{"skip", "later", "跳过", "稍后", "游客", "guest", "visitor", "试用", "trial", "try", "体验", "experience"}
	loginKeywords := []string{"login", "signin", "登录", "登陆"}

	for _, elem := range uiData.ClickableElements {
		combined := strings.ToLower(elem.Text + " " + elem.ResourceID + " " + elem.Label)

		for _, kw := range skipKeywords {
			if strings.Contains(combined, kw) {
				hasSkipLogin = true
				break
			}
		}

		for _, kw := range loginKeywords {
			if strings.Contains(combined, kw) {
				hasLoginButton = true
				break
			}
		}
	}

	// 动态计算建议操作数
	suggestedActions := CalculateMaxActions(uiData)

	// 构建Prompt
	prompt := fmt.Sprintf(`你是一个Android应用自动化测试专家。当前正在测试一个【%s】类应用的【%s】界面。

**任务目标**: 根据页面元素,设计%d个左右的交互动作(可以更多或更少,视实际情况而定),以触发尽可能多的网络请求(优先HTTP/HTTPS API调用)。

**重要提示**:
- 如果发现"同意/允许/确定"等权限按钮,**只返回点击这个按钮的一个动作即可**,因为点击后页面会跳转
- 避免在同一个页面上连续点击多个互斥按钮(如"同意"和"不同意")
- 优先执行会导致页面跳转的高价值动作

**当前界面分析**:
- 是否是主Activity: %t
- 是否有跳过登录选项: %t
- 是否有登录按钮: %t
- 是否有可浏览内容: %t

**UI可交互元素**:
%s

**输入框**:
%s

**交互策略要求**:
0. **🔥 系统"Open"按钮(超高优先级 - 优先级16)**:
   - **场景**: Android系统设置的"App info"页面
   - **必须最优先点击**: Open/打开/Launch/启动
   - **作用**: 从系统设置页面启动应用进入应用内部
   - **重要**: 如果界面有"Open", "Uninstall", "Force stop"三个按钮,只能点击"Open"!
1. **权限同意策略(最高优先级 - 优先级15)**:
   - **必须优先点击**: 同意/允许/确定/Accept/Allow/Agree/OK/授权/Grant/继续/Continue
   - **这些按钮通常在权限弹窗/服务协议/隐私政策页面出现**
   - **示例**: "同意并继续"(优先级15) vs "不同意"(禁止点击)
2. **登录策略(次高优先级 - 优先级14)** - 目标是在不登录情况下浏览APP:
   - **优先级14**: 点击"跳过登录/稍后/游客模式/试用/体验/免费试用/免登录体验/暂不登录/先逛逛"
   - **只在特殊情况点击登录**: 当前是主Activity且界面只有登录/注册按钮(无其他可点击内容)且没有跳过选项
   - **如果有可浏览内容**: 优先浏览内容,完全忽略登录按钮
   - **注意区分**: "登录"(Login/Sign in) vs "退出登录"(Sign out/Logout) - 后者不要点击
3. 优先点击高价值按钮: 搜索/刷新/分享/发送/查看详情/浏览/进入/更多 (优先级10-12)
4. **🚫 绝对禁止点击(优先级必须为0或不返回)**:
   - **拒绝类**: 拒绝/不同意/禁止/Deny/Refuse/Disagree/Decline
   - **否定类**: 否/不/No/Nope
   - **取消类**: 取消/Cancel
   - **退出类**: 返回/关闭/退出/退出登录/back/exit/quit/sign out/logout/close
   - **重要**: 如果界面同时有"同意"和"不同意"按钮,只能返回"同意"的点击动作!
5. 如果界面可滚动,优先滚动浏览内容 (优先级8)
6. 每个动作必须保证用户停留在APP内部,不能退出到桌面

**输出格式** (严格JSON数组):
` + "```json" + `
[
  {
    "type": "click",
    "x": 540,
    "y": 875,
    "reason": "点击登录按钮,触发认证API请求",
    "priority": 10
  },
  {
    "type": "input",
    "x": 540,
    "y": 500,
    "value": "test@example.com",
    "reason": "填写邮箱输入框",
    "priority": 9
  },
  {
    "type": "scroll",
    "direction": "down",
    "reason": "向下滚动加载更多内容",
    "priority": 5
  }
]
` + "```" + `

**注意**:
- 只返回JSON数组,不要其他解释
- priority范围1-16,数字越大越优先
- type只能是: click / input / scroll
- 坐标必须在屏幕范围内(0-1080, 0-2340)`,
		appCategory,
		activityName,
		suggestedActions,
		isMainActivity,
		hasSkipLogin,
		hasLoginButton,
		hasBrowsableContent,
		formatList(clickableSummary),
		formatList(inputSummary),
	)

	return prompt
}

// formatList 格式化列表
func formatList(items []string) string {
	if len(items) == 0 {
		return "(无)"
	}
	return strings.Join(items, "\n")
}

// callAI 调用AI API
func (e *InteractionEngine) callAI(ctx context.Context, prompt string) (string, error) {
	// 使用 glm-4v-flash 模型，禁用深度思考以加快响应
	reqBody := ChatRequest{
		Model:    "glm-4v-flash",
		Thinking: &ThinkingConfig{Type: "disabled"},
		Messages: []Message{
			{
				Role: "user",
				Content: []ContentPart{
					{
						Type: "text",
						Text: prompt,
					},
				},
			},
		},
	}

	resp, err := e.client.sendChatRequest(ctx, reqBody)
	if err != nil {
		return "", err
	}

	if len(resp.Choices) == 0 {
		return "", fmt.Errorf("no response from AI")
	}

	return resp.Choices[0].Message.Content, nil
}

// parseAIResponse 解析AI返回的JSON响应
func (e *InteractionEngine) parseAIResponse(response string, uiData *UIData) []Action {
	// 提取JSON (可能被```包裹，支持多行JSON)
	// (?s) 启用 DOTALL 模式，让 . 匹配换行符
	re := regexp.MustCompile("(?s)```json\\s*(\\[.*?\\])\\s*```")
	matches := re.FindStringSubmatch(response)

	var jsonStr string
	if len(matches) > 1 {
		jsonStr = matches[1]
	} else {
		// 尝试直接解析整个响应
		jsonStr = response
	}

	var actions []Action
	if err := json.Unmarshal([]byte(jsonStr), &actions); err != nil {
		e.logger.WithError(err).WithField("response", response[:min(len(response), 200)]).Warn("Failed to parse AI response")
		return []Action{}
	}

	// 禁止关键词列表
	forbiddenKeywords := []string{
		"返回", "back", "关闭", "close",
		"退出", "exit", "quit",
		"拒绝", "deny", "refuse", "不同意", "disagree", "decline",
		"禁止", "forbid", "否", "no", "nope", "取消", "cancel",
		"退出登录", "sign out", "logout",
	}

	// 验证和过滤
	validActions := []Action{}
	for _, action := range actions {
		// 检查类型
		if action.Type != "click" && action.Type != "input" && action.Type != "scroll" {
			continue
		}

		// 检查reason是否包含禁止关键词
		if action.Type == "click" {
			reason := strings.ToLower(action.Reason)
			isForbidden := false
			for _, kw := range forbiddenKeywords {
				if strings.Contains(reason, kw) {
					e.logger.WithField("reason", action.Reason).Info("Filtered forbidden action")
					isForbidden = true
					break
				}
			}
			if isForbidden {
				continue
			}
		}

		validActions = append(validActions, action)
	}

	// 按优先级排序 (从高到低)
	for i := 0; i < len(validActions); i++ {
		for j := i + 1; j < len(validActions); j++ {
			if validActions[j].Priority > validActions[i].Priority {
				validActions[i], validActions[j] = validActions[j], validActions[i]
			}
		}
	}

	return validActions
}

// fallbackStrategy 降级策略: 基于规则生成简单交互
func (e *InteractionEngine) fallbackStrategy(uiData *UIData, activityName string) []Action {
	actions := []Action{}

	// 判断是否是主Activity
	isMainActivity := strings.Contains(strings.ToLower(activityName), "main") ||
		strings.Contains(strings.ToLower(activityName), "launcher") ||
		strings.Contains(strings.ToLower(activityName), "splash") ||
		strings.Contains(strings.ToLower(activityName), "welcome")

	// 关键词列表
	openKeywords := []string{"open", "打开", "launch", "启动"}
	agreeKeywords := []string{"同意", "agree", "允许", "allow", "确定", "ok", "accept", "授权", "grant", "继续", "continue"}
	skipLoginKeywords := []string{"skip", "later", "跳过", "稍后", "游客", "guest", "visitor", "试用", "trial", "try", "体验", "experience"}
	loginKeywords := []string{"login", "signin", "登录", "登陆", "register", "注册"}
	highPriorityKeywords := []string{"搜索", "search", "刷新", "refresh", "分享", "share", "发送", "send", "查看", "view", "详情", "detail", "更多", "more"}
	forbiddenKeywords := []string{"返回", "back", "关闭", "close", "退出", "exit", "quit", "拒绝", "deny", "refuse", "不同意", "disagree", "禁止", "forbid", "否", "no", "取消", "cancel"}

	// 检查是否有跳过登录选项和可浏览内容
	hasSkipOption := false
	hasLoginOnly := true
	hasBrowsableContent := len(uiData.ClickableElements) > 5

	for _, elem := range uiData.ClickableElements {
		combined := strings.ToLower(elem.Label + " " + elem.Text + " " + elem.ResourceID)

		// 检测跳过登录选项
		for _, kw := range skipLoginKeywords {
			if strings.Contains(combined, kw) {
				hasSkipOption = true
				break
			}
		}

		// 如果有非登录按钮，说明不是纯登录页
		isLogin := false
		for _, kw := range loginKeywords {
			if strings.Contains(combined, kw) {
				isLogin = true
				break
			}
		}
		isSkip := false
		for _, kw := range skipLoginKeywords {
			if strings.Contains(combined, kw) {
				isSkip = true
				break
			}
		}

		if !isLogin && !isSkip && (elem.Text != "" || strings.Contains(elem.ResourceID, "btn") || strings.Contains(elem.ResourceID, "item")) {
			hasLoginOnly = false
		}
	}

	// 处理可点击元素
	for _, elem := range uiData.ClickableElements {
		if len(actions) >= 5 { // 降级策略最多5个动作
			break
		}

		combined := strings.ToLower(elem.Label + " " + elem.Text + " " + elem.ResourceID)

		// 检查是否禁止
		isForbidden := false
		for _, kw := range forbiddenKeywords {
			if strings.Contains(combined, kw) {
				isForbidden = true
				break
			}
		}
		if isForbidden {
			continue
		}

		// 判断优先级
		score := 5

		// Open按钮
		isOpen := false
		for _, kw := range openKeywords {
			if strings.Contains(combined, kw) {
				isOpen = true
				score = 16
				break
			}
		}

		// 权限同意
		isAgree := false
		if !isOpen {
			for _, kw := range agreeKeywords {
				if strings.Contains(combined, kw) {
					isAgree = true
					score = 15
					break
				}
			}
		}

		// 跳过登录
		isSkipLogin := false
		if !isOpen && !isAgree {
			for _, kw := range skipLoginKeywords {
				if strings.Contains(combined, kw) {
					isSkipLogin = true
					score = 14
					break
				}
			}
		}

		// 登录按钮 - 降低优先级，尽量避免点击
		isLogin := false
		if !isOpen && !isAgree && !isSkipLogin {
			for _, kw := range loginKeywords {
				if strings.Contains(combined, kw) {
					isLogin = true
					// 只在特定情况下点击登录，且优先级很低
					if isMainActivity && hasLoginOnly && !hasSkipOption {
						score = 3 // 降低优先级从8到3
					} else {
						continue // 跳过登录按钮
					}
					break
				}
			}
		}

		// 高价值按钮
		if !isOpen && !isAgree && !isSkipLogin && !isLogin {
			for _, kw := range highPriorityKeywords {
				if strings.Contains(combined, kw) {
					score = 10
					break
				}
			}
		}

		// 构建描述文本
		descText := elem.Label
		if descText == "" {
			descText = elem.Text
		}
		if descText == "" {
			parts := strings.Split(elem.ResourceID, "/")
			if len(parts) > 0 {
				descText = parts[len(parts)-1]
			}
		}
		if descText == "" {
			descText = "(无文本)"
		}

		actions = append(actions, Action{
			Type:     "click",
			X:        elem.Center[0],
			Y:        elem.Center[1],
			Reason:   fmt.Sprintf("点击按钮: %s", descText),
			Priority: score,
		})
	}

	// 如果有可浏览内容，添加滚动操作
	if hasBrowsableContent && len(uiData.ScrollableViews) > 0 {
		actions = append(actions, Action{
			Type:      "scroll",
			Direction: "down",
			Reason:    "向下滚动浏览更多内容",
			Priority:  12,
		})
	}

	// 排序
	for i := 0; i < len(actions); i++ {
		for j := i + 1; j < len(actions); j++ {
			if actions[j].Priority > actions[i].Priority {
				actions[i], actions[j] = actions[j], actions[i]
			}
		}
	}

	return actions
}

// ExecuteAction 执行单个动作 (需要ADB客户端配合)
type ActionExecutor interface {
	TapScreen(ctx context.Context, x, y int) error
	InputText(ctx context.Context, text string) error
	Shell(ctx context.Context, command string) (string, error)
	GetForegroundPackage(ctx context.Context) (string, error)
	StartActivity(ctx context.Context, component string) error
	PressBack(ctx context.Context) error
}

// ExecuteAction 执行动作
func (e *InteractionEngine) ExecuteAction(ctx context.Context, action Action, executor ActionExecutor) error {
	e.logger.WithFields(logrus.Fields{
		"type":     action.Type,
		"reason":   action.Reason,
		"priority": action.Priority,
	}).Info("Executing action")

	switch action.Type {
	case "click":
		return executor.TapScreen(ctx, action.X, action.Y)

	case "input":
		// 先点击输入框聚焦
		if err := executor.TapScreen(ctx, action.X, action.Y); err != nil {
			return err
		}
		time.Sleep(500 * time.Millisecond)
		// 输入文本
		return executor.InputText(ctx, action.Value)

	case "scroll":
		// 滚动操作
		var cmd string
		if action.Direction == "down" {
			cmd = "input swipe 540 1500 540 500 300"
		} else {
			cmd = "input swipe 540 500 540 1500 300"
		}
		_, err := executor.Shell(ctx, cmd)
		return err

	default:
		return fmt.Errorf("unknown action type: %s", action.Type)
	}
}

// min 返回最小值
func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

// ========== 操作安全检查相关函数 ==========

// PreCheckResult 操作前检查结果
type PreCheckResult struct {
	Safe       bool   // 是否安全可执行
	Reason     string // 拒绝原因（如果不安全）
	Element    *UIElement // 找到的目标元素（可能为nil）
}

// PreCheckAction 操作前检查
// 检查目标坐标的元素是否属于目标应用，避免误点击系统UI或其他应用
func (e *InteractionEngine) PreCheckAction(action Action, uiXML string, targetPackage string, screenWidth, screenHeight int) PreCheckResult {
	// 只检查点击操作
	if action.Type != "click" {
		return PreCheckResult{Safe: true, Reason: "非点击操作，跳过检查"}
	}

	// 1. 首先检查坐标是否在危险区域
	if IsDangerousZone(action.X, action.Y, screenWidth, screenHeight) {
		return PreCheckResult{
			Safe:   false,
			Reason: fmt.Sprintf("坐标(%d,%d)位于危险区域（状态栏/导航栏/边缘）", action.X, action.Y),
		}
	}

	// 2. 如果有 UI XML，查找目标元素并检查包名
	if uiXML != "" {
		element, err := FindElementByCoords(uiXML, action.X, action.Y)
		if err != nil {
			// 找不到元素，可能是坐标超出UI范围
			e.logger.WithError(err).WithFields(logrus.Fields{
				"x": action.X,
				"y": action.Y,
			}).Debug("无法找到坐标对应的元素")
			// 找不到元素时不阻止操作，可能是动态内容
			return PreCheckResult{Safe: true, Reason: "未找到元素，允许操作", Element: nil}
		}

		// 3. 检查元素是否安全
		if !IsElementSafe(element, targetPackage) {
			return PreCheckResult{
				Safe:    false,
				Reason:  fmt.Sprintf("元素属于其他应用(%s)，可能导致退出", element.Package),
				Element: element,
			}
		}

		return PreCheckResult{
			Safe:    true,
			Reason:  "元素安全",
			Element: element,
		}
	}

	// 没有 UI XML 数据，默认允许
	return PreCheckResult{Safe: true, Reason: "无UI数据，允许操作"}
}

// PostRecoveryCheck 操作后恢复检查
// 检查当前前台应用是否仍是目标应用，如果不是则尝试恢复
func (e *InteractionEngine) PostRecoveryCheck(ctx context.Context, executor ActionExecutor, targetPackage string, targetActivity string) error {
	// 等待操作完成和页面稳定
	time.Sleep(500 * time.Millisecond)

	// 检查当前前台应用
	currentPackage, err := executor.GetForegroundPackage(ctx)
	if err != nil {
		e.logger.WithError(err).Warn("无法获取前台应用包名")
		// 获取失败不阻塞流程
		return nil
	}

	// 如果仍在目标应用中，无需恢复
	if currentPackage == targetPackage {
		return nil
	}

	e.logger.WithFields(logrus.Fields{
		"current_package": currentPackage,
		"target_package":  targetPackage,
	}).Warn("应用已退出到其他应用，尝试恢复")

	// 尝试恢复（最多3次）
	for attempt := 1; attempt <= 3; attempt++ {
		var recoverErr error

		switch attempt {
		case 1:
			// 第一次：按返回键
			e.logger.Info("恢复尝试1: 按返回键")
			recoverErr = executor.PressBack(ctx)

		case 2:
			// 第二次：再按返回键
			e.logger.Info("恢复尝试2: 再次按返回键")
			recoverErr = executor.PressBack(ctx)

		case 3:
			// 第三次：强制启动目标 Activity
			e.logger.Info("恢复尝试3: 强制启动目标Activity")
			if targetActivity != "" {
				recoverErr = executor.StartActivity(ctx, targetActivity)
			} else {
				// 如果没有指定 Activity，尝试通过 monkey 启动主 Activity
				_, recoverErr = executor.Shell(ctx, fmt.Sprintf("monkey -p %s -c android.intent.category.LAUNCHER 1", targetPackage))
			}
		}

		if recoverErr != nil {
			e.logger.WithError(recoverErr).WithField("attempt", attempt).Warn("恢复操作执行失败")
			continue
		}

		// 等待恢复完成
		time.Sleep(1 * time.Second)

		// 再次检查前台应用
		currentPackage, err = executor.GetForegroundPackage(ctx)
		if err != nil {
			continue
		}

		if currentPackage == targetPackage {
			e.logger.WithField("attempt", attempt).Info("应用恢复成功")
			return nil
		}
	}

	// 恢复失败
	return fmt.Errorf("应用恢复失败：当前前台应用为 %s，目标应用为 %s", currentPackage, targetPackage)
}

// ExecuteActionSafe 安全执行动作（带前置检查和后置恢复）
// 这是 ExecuteAction 的增强版本，集成了安全检查机制
func (e *InteractionEngine) ExecuteActionSafe(ctx context.Context, action Action, executor ActionExecutor, targetPackage string, targetActivity string, uiXML string, screenWidth, screenHeight int) error {
	// 1. 操作前检查
	preCheck := e.PreCheckAction(action, uiXML, targetPackage, screenWidth, screenHeight)
	if !preCheck.Safe {
		e.logger.WithFields(logrus.Fields{
			"action_type": action.Type,
			"reason":      action.Reason,
			"reject_reason": preCheck.Reason,
			"x":           action.X,
			"y":           action.Y,
		}).Warn("操作被安全检查拦截，跳过此操作")
		return nil // 返回nil，不中断后续操作
	}

	// 记录通过检查的日志
	if preCheck.Element != nil {
		e.logger.WithFields(logrus.Fields{
			"action_type":     action.Type,
			"element_package": preCheck.Element.Package,
			"element_text":    preCheck.Element.Text,
		}).Debug("操作通过安全检查")
	}

	// 2. 执行操作
	err := e.ExecuteAction(ctx, action, executor)
	if err != nil {
		return err
	}

	// 3. 操作后恢复检查（仅对点击操作）
	if action.Type == "click" {
		if recoveryErr := e.PostRecoveryCheck(ctx, executor, targetPackage, targetActivity); recoveryErr != nil {
			e.logger.WithError(recoveryErr).Warn("应用恢复失败，可能影响后续分析")
			// 不返回错误，继续执行后续操作
		}
	}

	return nil
}

// ============================================
// 单步交互循环（新方案）
// ============================================

// SingleStepAction 单步操作结果
type SingleStepAction struct {
	Type      string `json:"type"`                // click, input, scroll, none
	X         int    `json:"x,omitempty"`         // 点击坐标X
	Y         int    `json:"y,omitempty"`         // 点击坐标Y
	Value     string `json:"value,omitempty"`     // input类型的输入值
	Direction string `json:"direction,omitempty"` // scroll方向: up/down/left/right
	Reason    string `json:"reason"`              // 操作原因
}

// PlanNextAction 单步交互：分析当前UI，返回1个最优操作
func (e *InteractionEngine) PlanNextAction(ctx context.Context, uiData *UIData, activityName string, step int, maxSteps int, history []*SingleStepAction) (*SingleStepAction, error) {
	// 【优先处理】检测登录页面的协议复选框（必须先勾选才能点击试用）
	checkboxAction := e.detectAgreementCheckbox(uiData, history)
	if checkboxAction != nil {
		e.logger.WithFields(logrus.Fields{
			"x":      checkboxAction.X,
			"y":      checkboxAction.Y,
			"reason": checkboxAction.Reason,
		}).Info("检测到协议复选框，优先点击")
		return checkboxAction, nil
	}

	// 构建精简提示词（包含历史操作）
	prompt := e.buildSingleStepPrompt(uiData, activityName, step, maxSteps, history)

	// 打印发送给AI的UI元素（方便调试）
	uiElements := e.formatUIElementsCompact(uiData)
	e.logger.WithFields(logrus.Fields{
		"activity":    activityName,
		"step":        step,
		"max_steps":   maxSteps,
		"ui_elements": len(uiData.ClickableElements),
	}).Info("AI单步分析请求")

	// 打印前500字符的UI元素信息
	uiPreview := uiElements
	if len(uiPreview) > 500 {
		uiPreview = uiPreview[:500] + "..."
	}
	e.logger.WithField("ui_preview", uiPreview).Info("发送给AI的UI元素")

	// 调用AI
	aiResponse, err := e.callAI(ctx, prompt)
	if err != nil {
		e.logger.WithError(err).Warn("AI调用失败，使用降级策略")
		return e.singleStepFallback(uiData), nil
	}

	// 打印AI原始响应
	responsePreview := aiResponse
	if len(responsePreview) > 300 {
		responsePreview = responsePreview[:300] + "..."
	}
	e.logger.WithField("ai_response", responsePreview).Info("AI原始响应")

	// 解析响应
	action, err := e.parseSingleStepResponse(aiResponse)
	if err != nil {
		e.logger.WithError(err).Warn("AI响应解析失败，使用降级策略")
		return e.singleStepFallback(uiData), nil
	}

	e.logger.WithFields(logrus.Fields{
		"type":   action.Type,
		"reason": action.Reason,
		"x":      action.X,
		"y":      action.Y,
	}).Info("AI返回单步操作")

	return action, nil
}

// buildSingleStepPrompt 构建单步交互提示词
func (e *InteractionEngine) buildSingleStepPrompt(uiData *UIData, activityName string, step int, maxSteps int, history []*SingleStepAction) string {
	// 简化UI元素信息
	uiElements := e.formatUIElementsCompact(uiData)

	// 构建历史操作信息
	historyStr := ""
	if len(history) > 0 {
		var historyLines []string
		for i, action := range history {
			if i >= 5 { // 最多显示最近5次操作
				break
			}
			historyLines = append(historyLines, fmt.Sprintf("- 第%d步: %s (%s)", i+1, action.Reason, action.Type))
		}
		historyStr = fmt.Sprintf("\n**已执行操作**:\n%s\n⚠️ 不要重复执行已做过的操作！如果复选框已点击过，接下来应该点击[试用/跳过]按钮。\n", strings.Join(historyLines, "\n"))
	}

	prompt := fmt.Sprintf(`你是Android自动化测试专家。分析当前界面，返回【1个最优操作】以触发网络请求。

**界面信息**:
- Activity: %s
- 第 %d/%d 步
%s
**UI元素（坐标已给出，必须使用这些坐标！）**:
%s

**策略规则（按优先级）**:
1. 如果复选框已点击过（看历史操作） → 直接点击"试用/跳过"按钮
2. 协议复选框 → 如果页面有"同意协议/隐私政策"文字，找到附近没有文字但有ID的小元素，这是复选框
3. 跳过登录/试用 → 点击（试用/跳过/游客/体验/先逛逛/暂不登录/稀后）
4. 系统Open按钮 → 点击进入应用（Open/打开/启动）
5. 权限/协议同意 → 必须点击（同意/允许/确定/Accept/Allow/OK/继续/我知道了）
6. 高价值按钮 → 触发请求（搜索/刷新/分享/详情/更多/查看/进入）
7. 导航Tab → 切换页面（首页/发现/推荐/我的/消息）
8. 滚动浏览 → 触发懒加载
9. 🚫 禁止点击：拒绝/不同意/取消/退出/返回/关闭/微信登录/QQ登录/手机登录/登录/注册

**⚠️ 重要规则**:
- x和y坐标必须从上面的UI元素列表中选择，不要自己编造坐标！
- 不要重复执行相同坐标的操作！
- 复选框识别：如果列表中有一个元素只有ID没有文字（如"ID:xxx 坐标:(212,1991)"），且附近有"协议/政策/同意"文字，这就是复选框

**输出**（严格JSON，只返回一个）:
{"type":"click","x":945,"y":125,"reason":"点击试用按钮跳过登录"}
{"type":"scroll","direction":"down","reason":"向下滚动加载更多"}
{"type":"none","reason":"纯展示页面，无可操作元素"}

只返回JSON，不要任何解释。`, activityName, step, maxSteps, historyStr, uiElements)

	return prompt
}

// detectAgreementCheckbox 检测登录页面的协议复选框
// 如果检测到未勾选的复选框，返回点击操作；否则返回nil
func (e *InteractionEngine) detectAgreementCheckbox(uiData *UIData, history []*SingleStepAction) *SingleStepAction {
	// 检查历史操作中是否已经点击过复选框
	for _, action := range history {
		if strings.Contains(action.Reason, "复选框") || strings.Contains(action.Reason, "checkbox") {
			return nil // 已经点击过复选框
		}
	}

	// 查找包含协议文字的元素
	var agreementElem *UIElement
	for i := range uiData.ClickableElements {
		elem := &uiData.ClickableElements[i]
		text := strings.ToLower(elem.Text + elem.Label)
		if strings.Contains(text, "同意") && (strings.Contains(text, "协议") || strings.Contains(text, "政策")) {
			agreementElem = elem
			break
		}
	}

	if agreementElem == nil {
		return nil // 没有找到协议文字
	}

	// 查找协议文字附近的小元素（可能是复选框）
	// 复选框通常在协议文字的左侧，Y坐标相近
	agreementY := agreementElem.Center[1]
	var checkboxElem *UIElement

	for i := range uiData.ClickableElements {
		elem := &uiData.ClickableElements[i]
		// 跳过有文字的元素（复选框通常没有文字）
		if elem.Text != "" || elem.Label != "" {
			continue
		}

		// 检查是否在协议文字左侧
		if elem.Center[0] >= agreementElem.Center[0] {
			continue
		}

		// 检查Y坐标是否接近（±100像素）
		yDiff := elem.Center[1] - agreementY
		if yDiff < 0 {
			yDiff = -yDiff
		}
		if yDiff > 100 {
			continue
		}

		// 检查元素大小（复选框通常是小元素）
		width := elem.Bounds[2] - elem.Bounds[0]
		height := elem.Bounds[3] - elem.Bounds[1]
		if width > 200 || height > 200 {
			continue
		}

		checkboxElem = elem
		break
	}

	if checkboxElem != nil {
		return &SingleStepAction{
			Type:   "click",
			X:      checkboxElem.Center[0],
			Y:      checkboxElem.Center[1],
			Reason: "点击协议复选框（必须先勾选才能继续）",
		}
	}

	return nil
}

// formatUIElementsCompact 格式化UI元素（紧凑版）
func (e *InteractionEngine) formatUIElementsCompact(uiData *UIData) string {
	var lines []string

	// 可点击元素（最多20个）
	for i, elem := range uiData.ClickableElements {
		if i >= 20 {
			lines = append(lines, fmt.Sprintf("... 还有 %d 个元素", len(uiData.ClickableElements)-20))
			break
		}

		text := elem.Label
		if text == "" {
			text = elem.Text
		}

		// 提取resource-id的最后部分
		resID := ""
		if elem.ResourceID != "" {
			parts := strings.Split(elem.ResourceID, "/")
			resID = parts[len(parts)-1]
		}

		line := fmt.Sprintf("%d. ", i+1)
		if text != "" {
			line += fmt.Sprintf("文本:\"%s\" ", text)
		}
		if resID != "" {
			line += fmt.Sprintf("ID:%s ", resID)
		}
		line += fmt.Sprintf("坐标:(%d,%d)", elem.Center[0], elem.Center[1])

		lines = append(lines, line)
	}

	// 输入框
	if len(uiData.InputFields) > 0 {
		lines = append(lines, "\n输入框:")
		for i, input := range uiData.InputFields {
			if i >= 5 {
				break
			}
			hint := input.Text
			if hint == "" {
				hint = "(无提示)"
			}
			lines = append(lines, fmt.Sprintf("  - %s 坐标:(%d,%d)", hint, input.Center[0], input.Center[1]))
		}
	}

	// 可滚动区域
	if len(uiData.ScrollableViews) > 0 {
		lines = append(lines, "\n页面可滚动")
	}

	if len(lines) == 0 {
		return "(无可交互元素)"
	}

	return strings.Join(lines, "\n")
}

// parseSingleStepResponse 解析单步响应
func (e *InteractionEngine) parseSingleStepResponse(response string) (*SingleStepAction, error) {
	// 清理响应，提取JSON
	response = strings.TrimSpace(response)

	// 尝试提取JSON（可能被```包裹）
	if strings.Contains(response, "```") {
		re := regexp.MustCompile("(?s)```(?:json)?\\s*(\\{.*?\\})\\s*```")
		matches := re.FindStringSubmatch(response)
		if len(matches) > 1 {
			response = matches[1]
		}
	}

	// 找到第一个 { 和最后一个 }
	start := strings.Index(response, "{")
	end := strings.LastIndex(response, "}")
	if start >= 0 && end > start {
		response = response[start : end+1]
	}

	var action SingleStepAction
	if err := json.Unmarshal([]byte(response), &action); err != nil {
		return nil, fmt.Errorf("JSON解析失败: %w, 原始响应: %s", err, response[:min(len(response), 200)])
	}

	// 验证type
	validTypes := map[string]bool{"click": true, "scroll": true, "input": true, "none": true}
	if !validTypes[action.Type] {
		return nil, fmt.Errorf("无效的操作类型: %s", action.Type)
	}

	// 验证坐标（click类型）
	if action.Type == "click" {
		if action.X <= 0 || action.Y <= 0 || action.X > 1440 || action.Y > 3200 {
			return nil, fmt.Errorf("无效的坐标: (%d, %d)", action.X, action.Y)
		}
	}

	return &action, nil
}

// ============================================
// AI交互循环主函数
// ============================================

// AILoopResult AI交互循环结果
type AILoopResult struct {
	TotalSteps      int                   // 总执行步数
	SuccessSteps    int                   // 成功执行步数
	ExitReason      string                // 退出原因
	Actions         []*SingleStepAction   // 执行的操作列表
	Errors          []string              // 错误列表
}

// UIDataProvider UI数据提供接口
type UIDataProvider interface {
	DumpUIHierarchy(ctx context.Context) (string, error)
	TakeScreenshot(ctx context.Context, path string) error
}

// RunAIInteractionLoop 执行AI单步交互循环
// 参数:
//   - ctx: 上下文
//   - executor: 动作执行器 (ADB客户端)
//   - uiProvider: UI数据提供器
//   - packageName: 目标应用包名
//   - activityName: 当前Activity名称
//   - maxSteps: 最大执行步数
//
// 返回:
//   - AILoopResult: 循环执行结果
func (e *InteractionEngine) RunAIInteractionLoop(
	ctx context.Context,
	executor ActionExecutor,
	uiProvider UIDataProvider,
	packageName string,
	activityName string,
	maxSteps int,
) *AILoopResult {
	result := &AILoopResult{
		Actions: make([]*SingleStepAction, 0),
		Errors:  make([]string, 0),
	}

	// 用于检测重复操作
	var lastAction *SingleStepAction
	sameActionCount := 0
	noneCount := 0 // 连续none计数

	e.logger.WithFields(logrus.Fields{
		"package":    packageName,
		"activity":   activityName,
		"max_steps":  maxSteps,
	}).Info("开始AI单步交互循环")

	for step := 1; step <= maxSteps; step++ {
		select {
		case <-ctx.Done():
			result.ExitReason = "上下文取消"
			e.logger.Info("AI交互循环: 上下文取消")
			return result
		default:
		}

		e.logger.WithField("step", step).Info("AI交互循环: 开始新一步")

		// 1. 检查当前是否在目标应用中
		currentPkg, err := executor.GetForegroundPackage(ctx)
		if err != nil {
			e.logger.WithError(err).Warn("获取前台应用失败")
			result.Errors = append(result.Errors, fmt.Sprintf("步骤%d: 获取前台应用失败: %v", step, err))
			// 尝试恢复
			if recoveryErr := e.recoverToApp(ctx, executor, packageName); recoveryErr != nil {
				result.ExitReason = "应用恢复失败"
				e.logger.WithError(recoveryErr).Error("AI交互循环: 应用恢复失败，退出")
				return result
			}
			continue
		}

		if currentPkg != packageName {
			e.logger.WithFields(logrus.Fields{
				"current": currentPkg,
				"target":  packageName,
			}).Warn("不在目标应用中，尝试恢复")

			if recoveryErr := e.recoverToApp(ctx, executor, packageName); recoveryErr != nil {
				result.ExitReason = "应用恢复失败"
				e.logger.WithError(recoveryErr).Error("AI交互循环: 应用恢复失败，退出")
				return result
			}
			continue
		}

		// 2. 获取UI数据
		uiXML, err := uiProvider.DumpUIHierarchy(ctx)
		if err != nil {
			e.logger.WithError(err).Warn("获取UI层级失败")
			result.Errors = append(result.Errors, fmt.Sprintf("步骤%d: 获取UI层级失败: %v", step, err))
			continue
		}

		// 3. 解析UI数据
		uiData, err := ParseUIXMLContent(uiXML)
		if err != nil {
			e.logger.WithError(err).Warn("解析UI层级失败")
			result.Errors = append(result.Errors, fmt.Sprintf("步骤%d: 解析UI层级失败: %v", step, err))
			continue
		}

		// 4. 调用AI获取下一步操作（传递历史操作，避免重复）
		action, err := e.PlanNextAction(ctx, uiData, activityName, step, maxSteps, result.Actions)
		if err != nil {
			e.logger.WithError(err).Warn("AI规划失败")
			result.Errors = append(result.Errors, fmt.Sprintf("步骤%d: AI规划失败: %v", step, err))
			continue
		}

		// 5. 检查是否为none（无操作）
		if action.Type == "none" {
			noneCount++
			e.logger.WithFields(logrus.Fields{
				"reason":     action.Reason,
				"none_count": noneCount,
			}).Info("AI返回none操作")

			// 连续3次none，退出循环
			if noneCount >= 3 {
				result.ExitReason = "连续3次无可操作元素"
				e.logger.Info("AI交互循环: 连续3次none，退出")
				return result
			}

			// 等待一下再继续
			time.Sleep(1 * time.Second)
			continue
		}

		// 重置none计数
		noneCount = 0

		// 6. 检查是否重复操作
		if lastAction != nil && isSameAction(lastAction, action) {
			sameActionCount++
			e.logger.WithFields(logrus.Fields{
				"action":     action.Type,
				"same_count": sameActionCount,
			}).Warn("检测到重复操作")

			if sameActionCount >= 3 {
				result.ExitReason = "连续3次相同操作"
				e.logger.Info("AI交互循环: 重复操作过多，退出")
				return result
			}
		} else {
			sameActionCount = 0
		}
		lastAction = action

		// 7. 执行操作
		execErr := e.executeSingleStepAction(ctx, action, executor, packageName, activityName, uiXML)
		if execErr != nil {
			e.logger.WithError(execErr).Warn("执行操作失败")
			result.Errors = append(result.Errors, fmt.Sprintf("步骤%d: 执行操作失败: %v", step, execErr))
			// 不退出，继续下一步
		} else {
			result.SuccessSteps++
		}

		result.TotalSteps = step
		result.Actions = append(result.Actions, action)

		// 8. 等待页面稳定
		time.Sleep(1500 * time.Millisecond)
	}

	result.ExitReason = "达到最大步数"
	e.logger.WithField("max_steps", maxSteps).Info("AI交互循环: 达到最大步数，退出")
	return result
}

// recoverToApp 尝试恢复到目标应用
func (e *InteractionEngine) recoverToApp(ctx context.Context, executor ActionExecutor, packageName string) error {
	// 尝试3次恢复
	for attempt := 1; attempt <= 3; attempt++ {
		e.logger.WithField("attempt", attempt).Info("尝试恢复到目标应用")

		var err error
		switch attempt {
		case 1:
			// 按返回键
			err = executor.PressBack(ctx)
		case 2:
			// 再按返回键
			err = executor.PressBack(ctx)
		case 3:
			// 通过monkey启动
			_, err = executor.Shell(ctx, fmt.Sprintf("monkey -p %s -c android.intent.category.LAUNCHER 1", packageName))
		}

		if err != nil {
			e.logger.WithError(err).Warn("恢复操作失败")
			continue
		}

		time.Sleep(1 * time.Second)

		// 检查是否恢复成功
		currentPkg, err := executor.GetForegroundPackage(ctx)
		if err == nil && currentPkg == packageName {
			e.logger.Info("应用恢复成功")
			return nil
		}
	}

	return fmt.Errorf("恢复到应用 %s 失败", packageName)
}

// executeSingleStepAction 执行单步操作
func (e *InteractionEngine) executeSingleStepAction(
	ctx context.Context,
	action *SingleStepAction,
	executor ActionExecutor,
	packageName string,
	activityName string,
	uiXML string,
) error {
	e.logger.WithFields(logrus.Fields{
		"type":   action.Type,
		"reason": action.Reason,
		"x":      action.X,
		"y":      action.Y,
	}).Info("执行单步操作")

	switch action.Type {
	case "click":
		// 安全检查
		preCheck := e.PreCheckAction(Action{
			Type: "click",
			X:    action.X,
			Y:    action.Y,
		}, uiXML, packageName, 1080, 2340)

		if !preCheck.Safe {
			e.logger.WithField("reason", preCheck.Reason).Warn("点击操作被安全检查拦截")
			return fmt.Errorf("操作被拦截: %s", preCheck.Reason)
		}

		// 执行点击
		if err := executor.TapScreen(ctx, action.X, action.Y); err != nil {
			return err
		}

		// 等待页面响应
		time.Sleep(500 * time.Millisecond)

		// 检查是否退出应用
		currentPkg, err := executor.GetForegroundPackage(ctx)
		if err == nil && currentPkg != packageName {
			e.logger.WithField("current_pkg", currentPkg).Warn("点击后退出了应用，尝试恢复")
			return e.recoverToApp(ctx, executor, packageName)
		}

	case "scroll":
		direction := action.Direction
		if direction == "" {
			direction = "down"
		}

		var cmd string
		switch direction {
		case "down":
			cmd = "input swipe 540 1500 540 500 300"
		case "up":
			cmd = "input swipe 540 500 540 1500 300"
		case "left":
			cmd = "input swipe 800 1000 200 1000 300"
		case "right":
			cmd = "input swipe 200 1000 800 1000 300"
		default:
			cmd = "input swipe 540 1500 540 500 300"
		}

		_, err := executor.Shell(ctx, cmd)
		if err != nil {
			return err
		}

	case "input":
		// 先点击输入框
		if err := executor.TapScreen(ctx, action.X, action.Y); err != nil {
			return err
		}
		time.Sleep(500 * time.Millisecond)

		// 输入文本
		if action.Value != "" {
			if err := executor.InputText(ctx, action.Value); err != nil {
				return err
			}
		}

	case "none":
		// 无操作
		return nil

	default:
		return fmt.Errorf("未知操作类型: %s", action.Type)
	}

	return nil
}

// isSameAction 判断两个操作是否相同
func isSameAction(a, b *SingleStepAction) bool {
	if a == nil || b == nil {
		return false
	}

	if a.Type != b.Type {
		return false
	}

	switch a.Type {
	case "click":
		// 坐标相差小于50认为是同一个位置
		return abs(a.X-b.X) < 50 && abs(a.Y-b.Y) < 50
	case "scroll":
		return a.Direction == b.Direction
	case "input":
		return a.Value == b.Value
	default:
		return true
	}
}

// singleStepFallback 单步降级策略
func (e *InteractionEngine) singleStepFallback(uiData *UIData) *SingleStepAction {
	// 优先级关键词
	priorityKeywords := []struct {
		keywords []string
		priority int
	}{
		{[]string{"open", "打开", "启动", "launch"}, 16},
		{[]string{"同意", "agree", "允许", "allow", "确定", "ok", "accept", "继续", "continue", "我知道了", "知道了"}, 15},
		{[]string{"跳过", "skip", "游客", "guest", "试用", "体验", "先逛逛", "暂不", "稀后", "later"}, 14},
		{[]string{"搜索", "search", "刷新", "refresh", "分享", "share", "详情", "detail", "更多", "more", "查看", "view"}, 12},
		{[]string{"首页", "home", "发现", "discover", "推荐", "我的", "mine", "消息", "message"}, 10},
	}

	// 禁止关键词
	forbiddenKeywords := []string{
		"拒绝", "deny", "不同意", "disagree", "取消", "cancel",
		"退出", "exit", "返回", "back", "关闭", "close",
		"登录", "login", "注册", "register", "signin", "signup",
	}

	var bestAction *SingleStepAction
	bestPriority := -1

	for _, elem := range uiData.ClickableElements {
		combined := strings.ToLower(elem.Text + " " + elem.Label + " " + elem.ResourceID)

		// 检查是否禁止
		isForbidden := false
		for _, kw := range forbiddenKeywords {
			if strings.Contains(combined, kw) {
				isForbidden = true
				break
			}
		}
		if isForbidden {
			continue
		}

		// 检查优先级
		for _, p := range priorityKeywords {
			for _, kw := range p.keywords {
				if strings.Contains(combined, kw) {
					if p.priority > bestPriority {
						bestPriority = p.priority
						text := elem.Label
						if text == "" {
							text = elem.Text
						}
						bestAction = &SingleStepAction{
							Type:   "click",
							X:      elem.Center[0],
							Y:      elem.Center[1],
							Reason: fmt.Sprintf("降级策略: 点击 %s", text),
						}
					}
					break
				}
			}
		}
	}

	// 如果没有找到高优先级按钮，尝试滚动
	if bestAction == nil && len(uiData.ScrollableViews) > 0 {
		return &SingleStepAction{
			Type:      "scroll",
			Direction: "down",
			Reason:    "降级策略: 向下滚动",
		}
	}

	// 如果还是没有，返回none
	if bestAction == nil {
		return &SingleStepAction{
			Type:   "none",
			Reason: "降级策略: 无可操作元素",
		}
	}

	return bestAction
}
