package ai

import (
	"context"
	"encoding/json"
	"fmt"
	"regexp"
	"strings"
	"time"

	"github.com/sirupsen/logrus"
)

// InteractionEngine AI驱动的交互引擎
type InteractionEngine struct {
	client *Client
	logger *logrus.Logger
}

// NewInteractionEngine 创建交互引擎
func NewInteractionEngine(apiKey string, logger *logrus.Logger) *InteractionEngine {
	return &InteractionEngine{
		client: NewClient(apiKey, logger),
		logger: logger,
	}
}

// Action 交互动作
type Action struct {
	Type     string `json:"type"`     // click, input, scroll
	X        int    `json:"x,omitempty"`
	Y        int    `json:"y,omitempty"`
	Value    string `json:"value,omitempty"`    // input类型的输入值
	Direction string `json:"direction,omitempty"` // scroll方向: up/down
	Reason   string `json:"reason"`
	Priority int    `json:"priority"` // 1-16, 数字越大越优先
}

// PlanActions 分析UI并生成交互策略
func (e *InteractionEngine) PlanActions(ctx context.Context, uiData *UIData, activityName string, appCategory string) ([]Action, error) {
	// 检查是否有可交互元素
	if len(uiData.ClickableElements) == 0 && len(uiData.InputFields) == 0 {
		e.logger.Info("No interactive elements found")
		return []Action{}, nil
	}

	// 构建Prompt
	prompt := e.buildAnalysisPrompt(uiData, activityName, appCategory)

	// 调用AI分析 (使用纯文本模式,不使用截图)
	aiResponse, err := e.callAI(ctx, prompt)
	if err != nil {
		e.logger.WithError(err).Warn("AI call failed, using fallback strategy")
		return e.fallbackStrategy(uiData, activityName), nil
	}

	// 解析AI响应
	actions := e.parseAIResponse(aiResponse, uiData)
	if len(actions) == 0 {
		e.logger.Warn("No actions generated by AI, using fallback")
		return e.fallbackStrategy(uiData, activityName), nil
	}

	// 动态限制操作数
	maxActions := CalculateMaxActions(uiData)
	if len(actions) > maxActions {
		actions = actions[:maxActions]
	}

	return actions, nil
}

// buildAnalysisPrompt 构建AI分析提示词
func (e *InteractionEngine) buildAnalysisPrompt(uiData *UIData, activityName string, appCategory string) string {
	// 判断是否是主Activity
	isMainActivity := strings.Contains(strings.ToLower(activityName), "main") ||
		strings.Contains(strings.ToLower(activityName), "launcher") ||
		strings.Contains(strings.ToLower(activityName), "splash") ||
		strings.Contains(strings.ToLower(activityName), "welcome")

	// 简化可点击元素信息
	clickableSummary := []string{}
	for i, elem := range uiData.ClickableElements {
		if i >= 15 { // 最多15个
			break
		}

		displayText := elem.Label
		if displayText == "" {
			displayText = elem.Text
		}

		resourceIDShort := ""
		if elem.ResourceID != "" {
			parts := strings.Split(elem.ResourceID, "/")
			if len(parts) > 0 {
				resourceIDShort = parts[len(parts)-1]
			}
		}

		classShort := ""
		if elem.Class != "" {
			parts := strings.Split(elem.Class, ".")
			if len(parts) > 0 {
				classShort = parts[len(parts)-1]
			}
		}

		summary := fmt.Sprintf("%d. ", i+1)
		if displayText != "" {
			summary += fmt.Sprintf("文本:\"%s\" ", displayText)
		}
		if resourceIDShort != "" {
			summary += fmt.Sprintf("ID:%s ", resourceIDShort)
		}
		summary += fmt.Sprintf("类型:%s 坐标:(%d,%d)", classShort, elem.Center[0], elem.Center[1])

		clickableSummary = append(clickableSummary, summary)
	}

	// 输入框信息
	inputSummary := []string{}
	for i, elem := range uiData.InputFields {
		if i >= 5 { // 最多5个
			break
		}

		summary := fmt.Sprintf("%d. ", i+1)
		if elem.Text != "" {
			summary += fmt.Sprintf("默认文本:\"%s\" ", elem.Text)
		}
		if elem.ResourceID != "" {
			parts := strings.Split(elem.ResourceID, "/")
			if len(parts) > 0 {
				summary += fmt.Sprintf("ID:%s ", parts[len(parts)-1])
			}
		}
		summary += fmt.Sprintf("坐标:(%d,%d)", elem.Center[0], elem.Center[1])

		inputSummary = append(inputSummary, summary)
	}

	// 检测特殊按钮
	hasSkipLogin := false
	hasLoginButton := false
	hasBrowsableContent := len(uiData.ClickableElements) > 5 || len(uiData.ScrollableViews) > 0

	skipKeywords := []string{"skip", "later", "跳过", "稍后", "游客", "guest", "visitor", "试用", "trial", "try", "体验", "experience"}
	loginKeywords := []string{"login", "signin", "登录", "登陆"}

	for _, elem := range uiData.ClickableElements {
		combined := strings.ToLower(elem.Text + " " + elem.ResourceID + " " + elem.Label)

		for _, kw := range skipKeywords {
			if strings.Contains(combined, kw) {
				hasSkipLogin = true
				break
			}
		}

		for _, kw := range loginKeywords {
			if strings.Contains(combined, kw) {
				hasLoginButton = true
				break
			}
		}
	}

	// 动态计算建议操作数
	suggestedActions := CalculateMaxActions(uiData)

	// 构建Prompt
	prompt := fmt.Sprintf(`你是一个Android应用自动化测试专家。当前正在测试一个【%s】类应用的【%s】界面。

**任务目标**: 根据页面元素,设计%d个左右的交互动作(可以更多或更少,视实际情况而定),以触发尽可能多的网络请求(优先HTTP/HTTPS API调用)。

**重要提示**:
- 如果发现"同意/允许/确定"等权限按钮,**只返回点击这个按钮的一个动作即可**,因为点击后页面会跳转
- 避免在同一个页面上连续点击多个互斥按钮(如"同意"和"不同意")
- 优先执行会导致页面跳转的高价值动作

**当前界面分析**:
- 是否是主Activity: %t
- 是否有跳过登录选项: %t
- 是否有登录按钮: %t
- 是否有可浏览内容: %t

**UI可交互元素**:
%s

**输入框**:
%s

**交互策略要求**:
0. **🔥 系统"Open"按钮(超高优先级 - 优先级16)**:
   - **场景**: Android系统设置的"App info"页面
   - **必须最优先点击**: Open/打开/Launch/启动
   - **作用**: 从系统设置页面启动应用进入应用内部
   - **重要**: 如果界面有"Open", "Uninstall", "Force stop"三个按钮,只能点击"Open"!
1. **权限同意策略(最高优先级 - 优先级15)**:
   - **必须优先点击**: 同意/允许/确定/Accept/Allow/Agree/OK/授权/Grant/继续/Continue
   - **这些按钮通常在权限弹窗/服务协议/隐私政策页面出现**
   - **示例**: "同意并继续"(优先级15) vs "不同意"(禁止点击)
2. **登录策略(次高优先级 - 优先级14)** - 目标是在不登录情况下浏览APP:
   - **优先级14**: 点击"跳过登录/稍后/游客模式/试用/体验/免费试用/免登录体验/暂不登录/先逛逛"
   - **只在特殊情况点击登录**: 当前是主Activity且界面只有登录/注册按钮(无其他可点击内容)且没有跳过选项
   - **如果有可浏览内容**: 优先浏览内容,完全忽略登录按钮
   - **注意区分**: "登录"(Login/Sign in) vs "退出登录"(Sign out/Logout) - 后者不要点击
3. 优先点击高价值按钮: 搜索/刷新/分享/发送/查看详情/浏览/进入/更多 (优先级10-12)
4. **🚫 绝对禁止点击(优先级必须为0或不返回)**:
   - **拒绝类**: 拒绝/不同意/禁止/Deny/Refuse/Disagree/Decline
   - **否定类**: 否/不/No/Nope
   - **取消类**: 取消/Cancel
   - **退出类**: 返回/关闭/退出/退出登录/back/exit/quit/sign out/logout/close
   - **重要**: 如果界面同时有"同意"和"不同意"按钮,只能返回"同意"的点击动作!
5. 如果界面可滚动,优先滚动浏览内容 (优先级8)
6. 每个动作必须保证用户停留在APP内部,不能退出到桌面

**输出格式** (严格JSON数组):
` + "```json" + `
[
  {
    "type": "click",
    "x": 540,
    "y": 875,
    "reason": "点击登录按钮,触发认证API请求",
    "priority": 10
  },
  {
    "type": "input",
    "x": 540,
    "y": 500,
    "value": "test@example.com",
    "reason": "填写邮箱输入框",
    "priority": 9
  },
  {
    "type": "scroll",
    "direction": "down",
    "reason": "向下滚动加载更多内容",
    "priority": 5
  }
]
` + "```" + `

**注意**:
- 只返回JSON数组,不要其他解释
- priority范围1-16,数字越大越优先
- type只能是: click / input / scroll
- 坐标必须在屏幕范围内(0-1080, 0-2340)`,
		appCategory,
		activityName,
		suggestedActions,
		isMainActivity,
		hasSkipLogin,
		hasLoginButton,
		hasBrowsableContent,
		formatList(clickableSummary),
		formatList(inputSummary),
	)

	return prompt
}

// formatList 格式化列表
func formatList(items []string) string {
	if len(items) == 0 {
		return "(无)"
	}
	return strings.Join(items, "\n")
}

// callAI 调用AI API
func (e *InteractionEngine) callAI(ctx context.Context, prompt string) (string, error) {
	// 使用 GLM-4.5-Flash 模型，禁用深度思考以加快响应
	reqBody := ChatRequest{
		Model:    "GLM-4.5-Flash",
		Thinking: &ThinkingConfig{Type: "disabled"},
		Messages: []Message{
			{
				Role: "user",
				Content: []ContentPart{
					{
						Type: "text",
						Text: prompt,
					},
				},
			},
		},
	}

	resp, err := e.client.sendChatRequest(ctx, reqBody)
	if err != nil {
		return "", err
	}

	if len(resp.Choices) == 0 {
		return "", fmt.Errorf("no response from AI")
	}

	return resp.Choices[0].Message.Content, nil
}

// parseAIResponse 解析AI返回的JSON响应
func (e *InteractionEngine) parseAIResponse(response string, uiData *UIData) []Action {
	// 提取JSON (可能被```包裹，支持多行JSON)
	// (?s) 启用 DOTALL 模式，让 . 匹配换行符
	re := regexp.MustCompile("(?s)```json\\s*(\\[.*?\\])\\s*```")
	matches := re.FindStringSubmatch(response)

	var jsonStr string
	if len(matches) > 1 {
		jsonStr = matches[1]
	} else {
		// 尝试直接解析整个响应
		jsonStr = response
	}

	var actions []Action
	if err := json.Unmarshal([]byte(jsonStr), &actions); err != nil {
		e.logger.WithError(err).WithField("response", response[:min(len(response), 200)]).Warn("Failed to parse AI response")
		return []Action{}
	}

	// 禁止关键词列表
	forbiddenKeywords := []string{
		"返回", "back", "关闭", "close",
		"退出", "exit", "quit",
		"拒绝", "deny", "refuse", "不同意", "disagree", "decline",
		"禁止", "forbid", "否", "no", "nope", "取消", "cancel",
		"退出登录", "sign out", "logout",
	}

	// 验证和过滤
	validActions := []Action{}
	for _, action := range actions {
		// 检查类型
		if action.Type != "click" && action.Type != "input" && action.Type != "scroll" {
			continue
		}

		// 检查reason是否包含禁止关键词
		if action.Type == "click" {
			reason := strings.ToLower(action.Reason)
			isForbidden := false
			for _, kw := range forbiddenKeywords {
				if strings.Contains(reason, kw) {
					e.logger.WithField("reason", action.Reason).Info("Filtered forbidden action")
					isForbidden = true
					break
				}
			}
			if isForbidden {
				continue
			}
		}

		validActions = append(validActions, action)
	}

	// 按优先级排序 (从高到低)
	for i := 0; i < len(validActions); i++ {
		for j := i + 1; j < len(validActions); j++ {
			if validActions[j].Priority > validActions[i].Priority {
				validActions[i], validActions[j] = validActions[j], validActions[i]
			}
		}
	}

	return validActions
}

// fallbackStrategy 降级策略: 基于规则生成简单交互
func (e *InteractionEngine) fallbackStrategy(uiData *UIData, activityName string) []Action {
	actions := []Action{}

	// 判断是否是主Activity
	isMainActivity := strings.Contains(strings.ToLower(activityName), "main") ||
		strings.Contains(strings.ToLower(activityName), "launcher") ||
		strings.Contains(strings.ToLower(activityName), "splash") ||
		strings.Contains(strings.ToLower(activityName), "welcome")

	// 关键词列表
	openKeywords := []string{"open", "打开", "launch", "启动"}
	agreeKeywords := []string{"同意", "agree", "允许", "allow", "确定", "ok", "accept", "授权", "grant", "继续", "continue"}
	skipLoginKeywords := []string{"skip", "later", "跳过", "稍后", "游客", "guest", "visitor", "试用", "trial", "try", "体验", "experience"}
	loginKeywords := []string{"login", "signin", "登录", "登陆", "register", "注册"}
	highPriorityKeywords := []string{"搜索", "search", "刷新", "refresh", "分享", "share", "发送", "send", "查看", "view", "详情", "detail", "更多", "more"}
	forbiddenKeywords := []string{"返回", "back", "关闭", "close", "退出", "exit", "quit", "拒绝", "deny", "refuse", "不同意", "disagree", "禁止", "forbid", "否", "no", "取消", "cancel"}

	// 检查是否有跳过登录选项和可浏览内容
	hasSkipOption := false
	hasLoginOnly := true
	hasBrowsableContent := len(uiData.ClickableElements) > 5

	for _, elem := range uiData.ClickableElements {
		combined := strings.ToLower(elem.Label + " " + elem.Text + " " + elem.ResourceID)

		// 检测跳过登录选项
		for _, kw := range skipLoginKeywords {
			if strings.Contains(combined, kw) {
				hasSkipOption = true
				break
			}
		}

		// 如果有非登录按钮，说明不是纯登录页
		isLogin := false
		for _, kw := range loginKeywords {
			if strings.Contains(combined, kw) {
				isLogin = true
				break
			}
		}
		isSkip := false
		for _, kw := range skipLoginKeywords {
			if strings.Contains(combined, kw) {
				isSkip = true
				break
			}
		}

		if !isLogin && !isSkip && (elem.Text != "" || strings.Contains(elem.ResourceID, "btn") || strings.Contains(elem.ResourceID, "item")) {
			hasLoginOnly = false
		}
	}

	// 处理可点击元素
	for _, elem := range uiData.ClickableElements {
		if len(actions) >= 5 { // 降级策略最多5个动作
			break
		}

		combined := strings.ToLower(elem.Label + " " + elem.Text + " " + elem.ResourceID)

		// 检查是否禁止
		isForbidden := false
		for _, kw := range forbiddenKeywords {
			if strings.Contains(combined, kw) {
				isForbidden = true
				break
			}
		}
		if isForbidden {
			continue
		}

		// 判断优先级
		score := 5

		// Open按钮
		isOpen := false
		for _, kw := range openKeywords {
			if strings.Contains(combined, kw) {
				isOpen = true
				score = 16
				break
			}
		}

		// 权限同意
		isAgree := false
		if !isOpen {
			for _, kw := range agreeKeywords {
				if strings.Contains(combined, kw) {
					isAgree = true
					score = 15
					break
				}
			}
		}

		// 跳过登录
		isSkipLogin := false
		if !isOpen && !isAgree {
			for _, kw := range skipLoginKeywords {
				if strings.Contains(combined, kw) {
					isSkipLogin = true
					score = 14
					break
				}
			}
		}

		// 登录按钮 - 降低优先级，尽量避免点击
		isLogin := false
		if !isOpen && !isAgree && !isSkipLogin {
			for _, kw := range loginKeywords {
				if strings.Contains(combined, kw) {
					isLogin = true
					// 只在特定情况下点击登录，且优先级很低
					if isMainActivity && hasLoginOnly && !hasSkipOption {
						score = 3 // 降低优先级从8到3
					} else {
						continue // 跳过登录按钮
					}
					break
				}
			}
		}

		// 高价值按钮
		if !isOpen && !isAgree && !isSkipLogin && !isLogin {
			for _, kw := range highPriorityKeywords {
				if strings.Contains(combined, kw) {
					score = 10
					break
				}
			}
		}

		// 构建描述文本
		descText := elem.Label
		if descText == "" {
			descText = elem.Text
		}
		if descText == "" {
			parts := strings.Split(elem.ResourceID, "/")
			if len(parts) > 0 {
				descText = parts[len(parts)-1]
			}
		}
		if descText == "" {
			descText = "(无文本)"
		}

		actions = append(actions, Action{
			Type:     "click",
			X:        elem.Center[0],
			Y:        elem.Center[1],
			Reason:   fmt.Sprintf("点击按钮: %s", descText),
			Priority: score,
		})
	}

	// 如果有可浏览内容，添加滚动操作
	if hasBrowsableContent && len(uiData.ScrollableViews) > 0 {
		actions = append(actions, Action{
			Type:      "scroll",
			Direction: "down",
			Reason:    "向下滚动浏览更多内容",
			Priority:  12,
		})
	}

	// 排序
	for i := 0; i < len(actions); i++ {
		for j := i + 1; j < len(actions); j++ {
			if actions[j].Priority > actions[i].Priority {
				actions[i], actions[j] = actions[j], actions[i]
			}
		}
	}

	return actions
}

// ExecuteAction 执行单个动作 (需要ADB客户端配合)
type ActionExecutor interface {
	TapScreen(ctx context.Context, x, y int) error
	InputText(ctx context.Context, text string) error
	Shell(ctx context.Context, command string) (string, error)
	GetForegroundPackage(ctx context.Context) (string, error)
	StartActivity(ctx context.Context, component string) error
	PressBack(ctx context.Context) error
}

// ExecuteAction 执行动作
func (e *InteractionEngine) ExecuteAction(ctx context.Context, action Action, executor ActionExecutor) error {
	e.logger.WithFields(logrus.Fields{
		"type":     action.Type,
		"reason":   action.Reason,
		"priority": action.Priority,
	}).Info("Executing action")

	switch action.Type {
	case "click":
		return executor.TapScreen(ctx, action.X, action.Y)

	case "input":
		// 先点击输入框聚焦
		if err := executor.TapScreen(ctx, action.X, action.Y); err != nil {
			return err
		}
		time.Sleep(500 * time.Millisecond)
		// 输入文本
		return executor.InputText(ctx, action.Value)

	case "scroll":
		// 滚动操作
		var cmd string
		if action.Direction == "down" {
			cmd = "input swipe 540 1500 540 500 300"
		} else {
			cmd = "input swipe 540 500 540 1500 300"
		}
		_, err := executor.Shell(ctx, cmd)
		return err

	default:
		return fmt.Errorf("unknown action type: %s", action.Type)
	}
}

// min 返回最小值
func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

// ========== 操作安全检查相关函数 ==========

// PreCheckResult 操作前检查结果
type PreCheckResult struct {
	Safe       bool   // 是否安全可执行
	Reason     string // 拒绝原因（如果不安全）
	Element    *UIElement // 找到的目标元素（可能为nil）
}

// PreCheckAction 操作前检查
// 检查目标坐标的元素是否属于目标应用，避免误点击系统UI或其他应用
func (e *InteractionEngine) PreCheckAction(action Action, uiXML string, targetPackage string, screenWidth, screenHeight int) PreCheckResult {
	// 只检查点击操作
	if action.Type != "click" {
		return PreCheckResult{Safe: true, Reason: "非点击操作，跳过检查"}
	}

	// 1. 首先检查坐标是否在危险区域
	if IsDangerousZone(action.X, action.Y, screenWidth, screenHeight) {
		return PreCheckResult{
			Safe:   false,
			Reason: fmt.Sprintf("坐标(%d,%d)位于危险区域（状态栏/导航栏/边缘）", action.X, action.Y),
		}
	}

	// 2. 如果有 UI XML，查找目标元素并检查包名
	if uiXML != "" {
		element, err := FindElementByCoords(uiXML, action.X, action.Y)
		if err != nil {
			// 找不到元素，可能是坐标超出UI范围
			e.logger.WithError(err).WithFields(logrus.Fields{
				"x": action.X,
				"y": action.Y,
			}).Debug("无法找到坐标对应的元素")
			// 找不到元素时不阻止操作，可能是动态内容
			return PreCheckResult{Safe: true, Reason: "未找到元素，允许操作", Element: nil}
		}

		// 3. 检查元素是否安全
		if !IsElementSafe(element, targetPackage) {
			return PreCheckResult{
				Safe:    false,
				Reason:  fmt.Sprintf("元素属于其他应用(%s)，可能导致退出", element.Package),
				Element: element,
			}
		}

		return PreCheckResult{
			Safe:    true,
			Reason:  "元素安全",
			Element: element,
		}
	}

	// 没有 UI XML 数据，默认允许
	return PreCheckResult{Safe: true, Reason: "无UI数据，允许操作"}
}

// PostRecoveryCheck 操作后恢复检查
// 检查当前前台应用是否仍是目标应用，如果不是则尝试恢复
func (e *InteractionEngine) PostRecoveryCheck(ctx context.Context, executor ActionExecutor, targetPackage string, targetActivity string) error {
	// 等待操作完成和页面稳定
	time.Sleep(500 * time.Millisecond)

	// 检查当前前台应用
	currentPackage, err := executor.GetForegroundPackage(ctx)
	if err != nil {
		e.logger.WithError(err).Warn("无法获取前台应用包名")
		// 获取失败不阻塞流程
		return nil
	}

	// 如果仍在目标应用中，无需恢复
	if currentPackage == targetPackage {
		return nil
	}

	e.logger.WithFields(logrus.Fields{
		"current_package": currentPackage,
		"target_package":  targetPackage,
	}).Warn("应用已退出到其他应用，尝试恢复")

	// 尝试恢复（最多3次）
	for attempt := 1; attempt <= 3; attempt++ {
		var recoverErr error

		switch attempt {
		case 1:
			// 第一次：按返回键
			e.logger.Info("恢复尝试1: 按返回键")
			recoverErr = executor.PressBack(ctx)

		case 2:
			// 第二次：再按返回键
			e.logger.Info("恢复尝试2: 再次按返回键")
			recoverErr = executor.PressBack(ctx)

		case 3:
			// 第三次：强制启动目标 Activity
			e.logger.Info("恢复尝试3: 强制启动目标Activity")
			if targetActivity != "" {
				recoverErr = executor.StartActivity(ctx, targetActivity)
			} else {
				// 如果没有指定 Activity，尝试通过 monkey 启动主 Activity
				_, recoverErr = executor.Shell(ctx, fmt.Sprintf("monkey -p %s -c android.intent.category.LAUNCHER 1", targetPackage))
			}
		}

		if recoverErr != nil {
			e.logger.WithError(recoverErr).WithField("attempt", attempt).Warn("恢复操作执行失败")
			continue
		}

		// 等待恢复完成
		time.Sleep(1 * time.Second)

		// 再次检查前台应用
		currentPackage, err = executor.GetForegroundPackage(ctx)
		if err != nil {
			continue
		}

		if currentPackage == targetPackage {
			e.logger.WithField("attempt", attempt).Info("应用恢复成功")
			return nil
		}
	}

	// 恢复失败
	return fmt.Errorf("应用恢复失败：当前前台应用为 %s，目标应用为 %s", currentPackage, targetPackage)
}

// ExecuteActionSafe 安全执行动作（带前置检查和后置恢复）
// 这是 ExecuteAction 的增强版本，集成了安全检查机制
func (e *InteractionEngine) ExecuteActionSafe(ctx context.Context, action Action, executor ActionExecutor, targetPackage string, targetActivity string, uiXML string, screenWidth, screenHeight int) error {
	// 1. 操作前检查
	preCheck := e.PreCheckAction(action, uiXML, targetPackage, screenWidth, screenHeight)
	if !preCheck.Safe {
		e.logger.WithFields(logrus.Fields{
			"action_type": action.Type,
			"reason":      action.Reason,
			"reject_reason": preCheck.Reason,
			"x":           action.X,
			"y":           action.Y,
		}).Warn("操作被安全检查拦截，跳过此操作")
		return nil // 返回nil，不中断后续操作
	}

	// 记录通过检查的日志
	if preCheck.Element != nil {
		e.logger.WithFields(logrus.Fields{
			"action_type":     action.Type,
			"element_package": preCheck.Element.Package,
			"element_text":    preCheck.Element.Text,
		}).Debug("操作通过安全检查")
	}

	// 2. 执行操作
	err := e.ExecuteAction(ctx, action, executor)
	if err != nil {
		return err
	}

	// 3. 操作后恢复检查（仅对点击操作）
	if action.Type == "click" {
		if recoveryErr := e.PostRecoveryCheck(ctx, executor, targetPackage, targetActivity); recoveryErr != nil {
			e.logger.WithError(recoveryErr).Warn("应用恢复失败，可能影响后续分析")
			// 不返回错误，继续执行后续操作
		}
	}

	return nil
}
